### PR TITLE
Fixed error after activating #42

### LINKED ISSUE #42: Error after activating
After activating this plugin https://i.imgur.com/xp32x4q.png

### PR DESCRIPTION
**Pull request by truong-mts**
Fixed #42

### CODE REVIEW

**Comment by truong-mts** [comment]
@mehfooz-a-mts I think instead of using `__FILE__`, we should add specific settings page's slug here https://github.com/MyThemeShopTeam/WP-Review/blob/master/admin/options.php#L9

**Comment by mehfooz-a-mts** [comment]
@truong-mts yes you are right. it adds the server path and can be an ugly URL. it should be replaced by a unique slug possibly by "wp-review" or "mts-wp-review.

**Comment by truong-mts** [comment]
@mehfooz-a-mts But I think we should keep `wp-review/admin/options.php` as slug because it will not break any user's modification

**Comment by mehfooz-a-mts** [comment]
@truong-mts I do not think changes are lost as we are just changing the page slug, not options here. Check this
http://take.ms/Ch1Qh
It did not affect any modifications.

**Comment by truong-mts** [comment]
@mehfooz-a-mts Assume a user enqueues a js file in the options page only, he can use options page slug to check. So I think we should keep the old slug.

This is fixed in v5.0.0 version so I will close this PR.

**Pull request closed without merging**
